
[types]

	[types.wood_type]

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.quark]
			azalea = true
			blossom = true

		[types.wood_type.deeperdarker]
			echo = true

		[types.wood_type.enlightened_end]
			congealed = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.byg]
			aspen = true
			baobab = true
			blue_enchanted = true
			bulbis = true
			cherry = true
			cika = true
			cypress = true
			ebony = true
			ether = true
			fir = true
			green_enchanted = true
			holly = true
			imparius = true
			lament = true
			jacaranda = true
			mahogany = true
			white_mangrove = true
			maple = true
			nightshade = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			willow = true
			witch_hazel = true
			zelkova = true
			sythian = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

	[types.leaves_type]

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			maple = true
			orange_autumn = true
			yellow_autumn = true
			rainbow_birch = true
			fir = true
			redwood = true
			white_cherry = true
			pink_cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.quark]
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.byg]
			araucaria = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			flowering_orchard = true
			flowering_palo_verde = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			joshua = true
			ripe_joshua = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			palo_verde = true
			pink_cherry = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			ripe_orchard = true
			silver_maple = true
			green_apple_skyris = true
			white_cherry = true
			yellow_birch = true
			yellow_spruce = true
			withering_oak = true
			flowering_nightshade = true
			firecracker = true
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			ether = true
			fir = true
			green_enchanted = true
			holly = true
			lament = true
			jacaranda = true
			mahogany = true
			white_mangrove = true
			maple = true
			nightshade = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.leaves_type.ad_astra]
			glacian = true

[entries]

	[entries.wood_type]

		[entries.wood_type.cfm]
			stripped_kitchen_sink_light = true
			table = true
			kitchen_counter = true
			coffee_table = true
			upgraded_gate = true
			park_bench = true
			stripped_park_bench = true
			cabinet = true
			stripped_kitchen_counter = true
			stripped_table = true
			mail_box = true
			stripped_cabinet = true
			kitchen_drawer = true
			desk = true
			stripped_bedside_cabinet = true
			blinds = true
			desk_cabinet = true
			stripped_kitchen_drawer = true
			stripped_chair = true
			upgraded_fence = true
			crate = true
			chair = true
			stripped_mail_box = true
			stripped_blinds = true
			kitchen_sink_dark = true
			stripped_kitchen_sink_dark = true
			bedside_cabinet = true
			stripped_desk_cabinet = true
			stripped_desk = true
			kitchen_sink_light = true
			stripped_coffee_table = true
			stripped_crate = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true

		[entries.wood_type.backpacked]
			backpack_shelf = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.farmersdelight]
			cabinet = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.cfm]
			hedge = true

